name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
    # You may pin to the exact commit or the version.
      # uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
      uses: docker/login-action@v2.1.0
      with:
        # Username used to log against the Docker registry
        username: atb9210 # optional
        # Password or personal access token used to log against the Docker registry
        password: ${{ secrets.DOKERHUB_TOKEN }} # optional
        # Specifies whether the given registry is ECR (auto, true or false)
        ecr: false # optional, default is auto
        # Log out from the Docker registry at the end of a job
        logout: true # optional, default is true
    - name: Docker Login
        
      run: docker build . --file Dockerfile --tag atb9210/telegram-bot:1.0
    - name: Push the docker image
      run : docker push atb9210/telegram-bot:1.0
